name: Java CI
on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Maven
        uses: actions/checkout@v3
        with:
         distribution: 'temurin'
         java-version: '17'
      - name: Build with Maven
        #run: mvn -B package --file pom.xml
        #run: mvn clean install
        run: mvn --batch-mode --update-snapshots verify
      - name: Test with Maven
        run:  mvn -Dtest=demoTask test
       #run: mvn '-Dtest=test.*Test' test
