name: Java CI
on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
jobs:
 build:
   runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner
   steps:
     - name: Checkout code
       uses: actions/checkout@v2  # Checks out your repository code
     - name: Set up JDK 17 (Adoptium)
       uses: adopt/setup-java@v2  # Sets up Java in the environment
       with:
         distribution: 'adopt'  # You can use 'adoptopenjdk', 'zulu', 'temurin', etc.
         java-version: '17'  # Specify the Java version you need (e.g., 8, 11, 17, etc.)
     - name: Verify Java installation
       run: Java -version
     - name: Set up Maven
       uses: actions/checkout@v2
       with:
         distribution: 'adopt'  # You can use 'adoptopenjdk', 'zulu', 'temurin', etc.
         java-version: '17'  # Specify the Java version you need (e.g., 8, 11, 17, etc.) 
     - name: Build with Maven
       run: mvn clean install  # This will build your Java project using Maven
     - name: Run tests
       run: mvn test  # This will run tests using Maven
