name: Java CI
on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
jobs:
 build:
   runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner
   steps:
     - name: Checkout code
       uses: actions/checkout@v3  # Checks out your repository code
     - name: Set up JDK 17 
       uses: actions/setup-java@v3  # Sets up Java in the environment
       with:
         distribution: 'temurin'  # You can use 'adoptopenjdk', 'zulu', 'temurin', etc.
         java-version: '17'  # Specify the Java version you need (e.g., 8, 11, 17, etc.)
     - name: Set up Maven
       uses: actions/checkout@v3
       with:
         distribution: 'temurin'  # You can use 'adoptopenjdk', 'zulu', 'temurin', etc.
         java-version: '17'  # Specify the Java version you need (e.g., 8, 11, 17, etc.) 
     - name: Build with Maven 
       run: mvn clean install  # This will build your Java project using Maven
     - name: Run tests with Maven
       run:  mvn -Dtest=demoTask test
     - name: Upload JUnit Test Report
       uses: actions/upload-artifact@v3
       with:
        name: junit-test-report
        path: target/surefire-reports/*.xml 
     - name: Upload HTML Test Report (Optional) 
       uses: actions/upload-artifact@v3 
       with: 
        name: html-test-report
        path: target/site/surefire-report.html

      
