name: Java CI
on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
jobs:
 build:
   runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner
   steps:
     - name: Checkout code
       uses: actions/checkout@v3  # Checks out your repository code
     - name: Set up JDK 17 
       uses: actions/setup-java@v3  # Sets up Java in the environment
       with:
         distribution: 'temurin'  # You can use 'adoptopenjdk', 'zulu', 'temurin', etc.
         java-version: '17'  # Specify the Java version you need (e.g., 8, 11, 17, etc.)
     - name: Install Chrome dependencies
       run: |
         sudo apt-get update
         sudo apt-get install -y wget curl unzip
         sudo apt-get install -y libx11-xcb1 libxcomposite1 libxdamage1 libxrandr2 libgbm1
     - name: Install Chrome
       run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
     - name: Set up Maven
       uses: actions/checkout@v3
       with:
         distribution: 'temurin'  # You can use 'adoptopenjdk', 'zulu', 'temurin', etc.
         java-version: '17'  # Specify the Java version you need (e.g., 8, 11, 17, etc.) 
     - name: Build with Maven 
       run: mvn clean install  # This will build your Java project using Maven
       #run: mvn --batch-mode --update-snapshots verify
     - name: Run tests with Maven
      # run: mvn test # This will run tests using Maven
       run:  mvn -Dtest=demoTask test
