name: Java CI
on:
 push:
   branches:
     - master
 pull_request:
   branches:
     - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v3
        with:
         distribution: 'temurin'
         java-version: '17'
      - run: mvn clean install
      - run: mvn test
